export const projectsMap = [
  {
    id: 1,
    keyName: 'audiophile-react',
    name: 'ecommerce website',
    tags: ['REACT', 'TYPESCRIPT', 'SASS', 'REACT QUERY'],
    image: 'images/audiophile.jpg',
  },
  {
    id: 2,
    keyName: 'Fullstack-Todo-list-react',
    name: 'Advanced fullstack task manager',
    tags: ['REACT', 'FIREBASE', 'STYLED-COMPONENTS', 'REDUX'],
    image: 'images/todo-list.jpg',
  },
  {
    id: 3,
    keyName: 'rest-countries-react',
    name: 'country finder',
    tags: ['REACT', 'TYPESCRIPT', 'STYLED-COMPONENTS', 'REACT QUERY'],
    image: 'images/countries.jpg',
  },
  {
    id: 4,
    keyName: 'movies-browser',
    name: 'movies browser',
    tags: ['REACT', 'TYPESCRIPT', 'STYLED-COMPONENTS', 'REDUX', 'REACT QUERY'],
    image: 'images/movies-browser.jpg',
  },
  {
    id: 5,
    keyName: 'currency-converter-react',
    name: 'currency converter',
    tags: ['REACT', 'TYPESCRIPT', 'STYLED-COMPONENTS', 'REACT QUERY'],
    image: 'images/currency-converter.jpg',
  },
  {
    id: 6,
    keyName: 'quizzical-react',
    name: 'quizz game',
    tags: ['REACT', 'TYPESCRIPT', 'STYLED-COMPONENTS', 'REDUX'],
    image: 'images/quizzical.jpg',
  },
  {
    id: 7,
    keyName: 'space-tourism-react',
    name: 'space tourism',
    tags: ['REACT', 'TYPESCRIPT', 'STYLED-COMPONENTS'],
    image: 'images/space-tourism.jpg',
  },
  {
    id: 8,
    keyName: 'Huddle-react',
    name: 'landing page',
    tags: ['REACT', 'TYPESCRIPT', 'STYLED-COMPONENTS'],
    image: 'images/huddle.jpg',
  },
];
